### ISSUE TITLE
Cannot boot into mac recovery

### ISSUE THREAD

**Issue by ItsDan001** [MultimediaLucario/Lenovo-ThinkPad-T480#1]
When booting off the pendrive, the apple logo appears, it loads for a bit and then the laptop restarts. Ive done everything as it is in the guide, i also have a i5-8350U. I am using a 8gb Philips usb, if that matters. Also tried the original valnoxy repo and same issue is apparent. I tried many things, nothing works. I have disabled thunderbolt with the kexts provided in the config.plist, also have enabled/disabled all the things mentioned in the guide. I am using the Ventura images

**Comment by michal161** [comment]
hey, how did you managed to boot it?

**Comment by ItsDan001** [comment]
oh sorry! i forgot to mention how lol. Pretty much replaced the m.2 ssd that came with the laptop, with a new one. Have no idea how that helped but seems to be the problem because, when i put back the old ssd, the issue appeared again.

**Comment by michal161** [comment]
Weird. I managed to boot yesterday. By creating usb using gibmacos instead of macrecovery and then updated from macos catalina to macos Sonoma. By the time i have found someone who rebuilt this efi. Which included some lines to boot windows from open core recovery. Thanks for replying btw.
