### ISSUE TITLE
Hard restart after entering password

### ISSUE THREAD

**Issue by khlivnyi** [MultimediaLucario/Lenovo-ThinkPad-T480#10]
**Describe the bug**
After boot from provided EFI for sonoma getting Hard restart after entering password

**Comment by itsndannn** [comment]
Same issue here. after entering my password, my thinkpad reboots. This issue persists in both 1.5.1 and 1.6.0 versions of the Sonoma EFI. I have not tested other versions. My thinkpad doesn't do that when using the "EFI - Intel" efi, that supports Ventura, but the Wi-Fi does not work
