### ISSUE TITLE
Wrong patches in manual?

### ISSUE THREAD

**Issue by khlivnyi** [MultimediaLucario/Lenovo-ThinkPad-T480#11]
Hello, in installation guide those patches are described as installed: 
SSDT-ARPT.aml 	Broadcom cards 	Disable Broadcom card during sleep
SSDT-OFFTB.aml 	Thunderbolt 	Disable Thunderbolt
SSDT-OFFGDGPU.aml 	NVIDIA GeForce MX 150 	Disable NVIDIA GPU (necessary if installed)

 but in reality I've got those in sonoma efi:

SSDT-KBRD.aml
SSDT-TbtOnPch-ThinkPad-T480-OC-DTPG.aml
SSDT-Thinkpad_T480.aml

trying to do clean install in my system and it just resets after loading new system image via regular install with yellow gears boot from opencore, maybe someone have description for these? 

T480 
Intel© Core™ i7-8550U CPU @ 1.80GHz × 4
Intel Corporation UHD Graphics 620

thanks in advance

**Comment by m6s** [comment]
I have the same problem. I can get into Ventura recovery with `EFI - Intel` but not into Sonoma recovery with `EFI - Sonoma/EFI`. Sonoma recovery just reboots at the end of the loading screen.

Sonoma recovery *does* load with `EFI - Intel`, but unfortunately has no wifi.

Also wondering about the sources of those AMLs, I googled but couldn't find anything. (Not that that would help me much, I'm new to OpenCore/Hackintoshes)

Intel Core i5-8350U 
Intel UHD Graphics 620  (WXGA)
Intel SSDPEKKF512G8L M.2 NVMe SSD 
Fibocom L850-GL (LTE)

**Comment by khlivnyi** [comment]
> I have the same problem. I can get into Ventura recovery with `EFI - Intel` but not into Sonoma recovery with `EFI - Sonoma/EFI`. Sonoma recovery just reboots at the end of the loading screen.
> 
> Sonoma recovery _does_ load with `EFI - Intel`, but unfortunately has no wifi.
> 
> Also wondering about the sources of those AMLs, I googled but couldn't find anything. (Not that that would help me much, I'm new to OpenCore/Hackintoshes)
> 
> Intel Core i5-8350U  Intel UHD Graphics 620  (WXGA) Intel SSDPEKKF512G8L M.2 NVMe SSD  Fibocom L850-GL (LTE)

To fix wifi leave only one airportltlwm for Ventura https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.2.0 and delete another if any
