### ISSUE TITLE
Success on sonoma 4.1.1 but failed on sonoma 4.4.1

### ISSUE THREAD

**Issue by hinzdc** [MultimediaLucario/Lenovo-ThinkPad-T480#13]
Efi - sonoma glitch and force restart on 

On sonoma 4.1.1 it runs fine. But on Sonoma 4.4.1 it always force restarts accompanied by a glitch.

**Comment by khlivnyi** [comment]
> Efi - sonoma glitch and force restart on
> 
> On sonoma 4.1.1 it runs fine. But on Sonoma 4.4.1 it always force restarts accompanied by a glitch.

Security -> SecureBootModel is set to disabled?

**Comment by ImBlu3** [comment]
I had the same issue, the above fixed it, but had to use heliport, but it is honestly better
