### ISSUE TITLE
Questions: Thinkpad Dock requirements, dual boot, Secure boot

### ISSUE THREAD

**Issue by samveen** [MultimediaLucario/Lenovo-ThinkPad-T480#14]
- Is anything extra required to use the T480 with the Thinkpad dock with a Monitor, Keyboard, Mouse?
- What extra steps need to be taken to allow retaining the Win10 installed on the boot disk, and dualbooting to it?
- As win10 complains about secure-boot being disabled, is there anything that can be done to keep secure-boot enabled, but install a SecureBoot Machine Owner Key (MOK) and use that to sign the opencore boot-up artefacts?

**Comment by MultimediaLucario** [comment]
There is nothing else required to use the dock.
