### ISSUE TITLE
Panics in MacOS Setup

### ISSUE THREAD

**Issue by jailbreakmerebooted** [MultimediaLucario/Lenovo-ThinkPad-T480#17]
Lenovo T480
Intel Core I7 pro 8th gen
Intel Graphics UHD 620/Nvidia GeForce MX130
32GB Ram
1TB M.2 SSD

I have an big issue.
I tried using EFI-Intel and the kernel panics while installing macOS Ventura 13.6.2.

I am booting Opencore Raw from my usb where macOS is located too. I tried disabling some ACPI patches and enabling them without success.

I installed it on my disk using MacOS Jornaled Extended. When I try to format as APFS I get a straight panic.

**Comment by MultimediaLucario** [comment]
This was soley forked for Intel Core I5 models.

**Comment by Pete466** [comment]
you could try to set the SecureBoot to "Disabled" instead of "Default", then the installation should run. I don't know about the i7, but for that it should be possible to replace the ACPI files from another Github-EFI and Snapshot with ProperTree
