### ISSUE TITLE
after update the opencore to 1.0.0 i lost wifi connection

### ISSUE THREAD

**Issue by AbuYousof26** [MultimediaLucario/Lenovo-ThinkPad-T480#18]
hello guys 
hope you everyone doing good

while i am running on before 1.0.0 everything is working perfectly but after update the open core to 1.0.0 by OCAT tools i get an issue with wifi that it is not running like if it is no driver.

please support

**Comment by AbuYousof26** [comment]
anyone can help ?

**Comment by dimka4996** [comment]
i installed yesterday last efi ventura and have no connection, after manual update airportitwl kext it's working fine

**Comment by MultimediaLucario** [comment]
Use Itlwm.kext and HeliPort.
