### ISSUE TITLE
transparencyd process high cpu usage.

### ISSUE THREAD

**Issue by alanthecodermac** [MultimediaLucario/Lenovo-ThinkPad-T480#19]
The 'transparencyd' process causes the cpu to spike continuously at 100%+

signing in with appleid in system settings reproduces the problem

Using the latest EFI as of 27.05.2024

partial solution
signing out of appleid mitigates the issue but with the loss of apple icloud services such as apple store, messages

EDIT:issue seems to be resolved after OS update from 14.3.1 -> 14.5

**Comment by hinzdc** [comment]
I've experienced this and found a solution on reddit.
You can enter commands in the terminal.

`sudo launchctl disable gui/501/com.apple.transparencyd`

then reboot.

ref:
https://www.reddit.com/r/hackintosh/comments/1alhh5f/comment/kpisxv9/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
