### ISSUE TITLE
Add i7 Note to preparation

### ISSUE THREAD

**Issue by ImBlu3** [MultimediaLucario/Lenovo-ThinkPad-T480#24]
I used an i7 Thinkpad T480, with secureboot set to disabled in the plist, as else, I would end up in A bootloop caused by AppleSMC.

I hope you could add a note for the i7 models in the preparation to use the heliport efi if an intel card is installed, and disable SecureBoot in the plist.

**Comment by MultimediaLucario** [comment]
I just put out a note.
