### ISSUE TITLE
Weird Touchpad behaviour

### ISSUE THREAD

**Issue by Matchbox0302** [MultimediaLucario/Lenovo-ThinkPad-T480#26]
Description of the bug:

Touchpad is unresponsive and slow, scrolling gestures work but are slow and don't scroll the page as they should (inertial scrolling doesn't work). Touchpad gestures don't work (gesture to open launchpad, gesture to change fullscreen apps and spaces) touch to click also doesn't work. Everything else work as intended and is very smooth.

My specs: 

T480
i5 8350U
16GB of ram
Intel Dual Band Wireless-AC 8265
Synaptics UltraNav touchpad

I'm willing to give any information necessary, would love to use your EFI as it is the best. Thanks.

**Comment by MultimediaLucario** [comment]
I am currently working on trying to patch the EFI as it is taking a little long than usual due to other circumstances but I will issue an update as soon as possible.
