### ISSUE TITLE
Slow download speed in ventura, when using any apple app, issue is not present in non-apple apps

### ISSUE THREAD

**Issue by G4-Synix** [MultimediaLucario/Lenovo-ThinkPad-T480#27]
This issue shows on all apple apps, right now im downloading garageband for example, and the download speed is abysmal, it's been downloading for a bit now and it's still at 43mb, going at 0.1mb at a time, but, if i were to download something from firefox (which is the browser i am currently using), it'd take no time and download at full speed (40MB/s+)

**Comment by MultimediaLucario** [comment]
I just dropped a new release. It should make things more stable.
