### ISSUE TITLE
Dualbooting not working via Opencore on Windows

### ISSUE THREAD

**Issue by tetenc555** [MultimediaLucario/Lenovo-ThinkPad-T480#29]
Using a system with only one SSD, it is possible to install both systems, if you keep switching between them via the BIOS picker. Using opencore throws a ACPI_BIOS_ERROR bsod,which means one (or maybe more) ACPI patches are breaking booting Windows. This breaks using bootcamp tô switch between systems, and it can be fixed with "Ifs" on the patches itself (which i'm trying to apply right now in my build). Tried on Sonoma x Windows 11, with the Sequoia variant of the EFI, after upgrading it to 1.0.2.

**Comment by MultimediaLucario** [comment]
Thank you for bringing this to my attention. I'll be sure to work on an update ASAP.

**Comment by tetenc555** [comment]
just to mention: I had to disable SSDT-AC on ACPI -> Add and SLEEP: GRPW(2,N) to ZRPW on ACPI -> Patch
Then I started getting a different BSOD "SYSTEM_HANDLE_EXCEPTION_ERROR" which I fixed by messing with the Booter Quirks
